Add ability to create File objects from existing files (#11)
Jonxslays/piston_rs pull request #12
Opened 2021-12-29 19:12 UTC by parafoxia

This PR:

* Adds the `load_from` classmethod and the `load_contents_from` method to load contents from existing files (it also adds a private `load_contents` method which the two public methods share)
* Corrects some issues in the docs
* Adds relevant tests

Closes #11.

2021-12-30 02:43 UTC, Jonxslays requested changes
The tests would need to be adjust a bit for this too.

2021-12-30 02:43 UTC, Jonxslays commented on src/lib.rs
> +    pub fn load_from(path: &str) -> Self {
Rather than making the decision to just print and return a default `File` here, I would prefer if we passed an error back up to the user to handle how they see which (which may or may not include using a default file). 

We will need to use `std::error`, and probably `std::io::Error`, and the appropriate `std::io::ErrorKind` for the errors. 

Alternatively, if you dont want to use the built in errors, you can create a struct to represent a `FileLoadError` that we make. It will need to inplement the `Display` trait if we go this route. 

```suggestion
    pub fn load_from(path: &str) -> Result<Self, Box<dyn error::Error>> {
```

2021-12-30 02:43 UTC, Jonxslays commented on src/lib.rs
> +        }
This would return an Err() with a Box::new Error::new()

2021-12-30 02:43 UTC, Jonxslays commented on src/lib.rs
> +        };
here you can match on file_name like you are, but then use to_string_lossy() to account for weird characters and return an Err() Box::new(Error::new(...)) if it is None

2021-12-30 02:43 UTC, Jonxslays commented on src/lib.rs
> +        }
This would be wrapped in Ok()

2021-12-30 02:43 UTC, Jonxslays commented on src/lib.rs
> +    }
Here propagating the Result is much easier

```suggestion
    fn load_contents(path: &Path) -> Result<String, Box<dyn error::Error>> {
        Ok(fs::read_to_string(&path)?)
    }
```

2021-12-30 02:43 UTC, Jonxslays commented on src/lib.rs
> +
Here you would change the return type to Result as well, and add a `?` like `load_contents(&path)?`

2021-12-30 03:21 UTC, Jonxslays commented
Leaving this here for reference:

```rs
type LoadResult<T> = Result<T, LoadError>;

#[derive(Debug, Clone)]
pub struct LoadError {
    message: String,
}

impl LoadError {
    fn new(message: &str) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl std::fmt::Display for LoadError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}
```

2021-12-30 12:56 UTC, Jonxslays commented on src/lib.rs
> +    fn load_contents(path: &Path) -> String {
Can we also get a Docstring on this function. The examples section can have an `ignore` right after the backticks, so they dont run (fail due to private function) but would still like the private functions documented.

2021-12-30 14:29 UTC, Jonxslays commented on src/lib.rs
> +        match fs::read_to_string(&path) {
The reference isn't needed here I just realized, because it is already a reference.
```suggestion
        match fs::read_to_string(path) {
```

2021-12-30 22:42 UTC, parafoxia commented
Anything marked as resolved I've done locally, but may not have pushed yet.

2021-12-31 00:09 UTC, Jonxslays approved these changes

2021-12-31 00:09 UTC, merged